### PR TITLE
Fix Django 3.1 compatibility

### PR DESCRIPTION
**Pull request by yakky**
#26 didn't test Django 3.1 compatibility to the missing version bump in setup.py

### CODE REVIEW

**Comment by yakky** [comment]
@victor-yunenko could you review this?

**Review by FinalAngel — APPROVED** [review]

**Comment by FinalAngel** [comment]
@yakky all good from my end. I would recommend removing the ``'Django>=1.11,<3.2',`` restraint altogether (makes debugging and getting early feedback easier)

**Comment by yakky** [comment]
@FinalAngel  seems legit
Patch updated

**Comment by victor-yunenko** [comment]
> I would recommend removing the 'Django>=1.11,<3.2'

I agree, I used to do it myself, but on a mature packaging system (eg `cargo` I guess) setting an upper boundary helps, while with pip the compilation of requirements simply fails :(

**Comment by andymccurdy** [comment]
FYI I made a new django-appdata release (0.3.1) to PyPI with this change.

**Pull request merged**
