### PR TITLE
Update to Django 2.2 / Python 3.7

### PR DESCRIPTION
**Pull request by yakky**
Only tox / travis updates needed

### CODE REVIEW

**Comment by yakky** [comment]
@FinalAngel could you give an eye on this?

**Comment by FinalAngel** [comment]
👍

**Comment by palmitoto** [comment]
Hi,

could you upload the latest release on Pypi ?
Thanx

**Comment by yakky** [comment]
@FinalAngel I have no upload rights on PyPi, could you upload the version?

**Comment by FinalAngel** [comment]
@yakky done, 0.2.2 uploaded

**Comment by palmitoto** [comment]
@FinalAngel @yakky thanks you !

**Pull request merged**
