### PR TITLE
Add support for Django 3.0

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by yakky** [comment]
@finalangel could you review this?

**Comment by pupattan** [comment]
any expected date to get this merged ?

**Comment by yakky** [comment]
@pupattan now :)
Hopefully we will have a release later today

**Comment by yakky** [comment]
@kinkerl :bow:

**Comment by pupattan** [comment]
Thank you very much 

> @pupattan now :)
> Hopefully we will have a release later today

**Pull request merged**
