### PR TITLE
Add tests for Django 3.1

### PR DESCRIPTION
**Pull request by yakky**
No code change required

### CODE REVIEW

**Comment by yakky** [comment]
@FinalAngel could you review this?

**Review by FinalAngel — APPROVED** [review]
@yakky 👍

**Comment by victor-yunenko** [comment]
@yakky, the setup.py still has `django < 3.1` line in it though :)

**Comment by yakky** [comment]
@victor-yunenko :man_facepalming: See #27

**Comment by yakky** [comment]
@victor-yunenko unfortunately there are some issues I am investigating with Django 3.1

**Pull request merged**
